// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config 应用配置
 */
export interface Config {
    /**
     * 保存目录
     */
    "saveDirectory": string;

    /**
     * 文件名格式
     */
    "filenameTemplate": string;

    /**
     * 图片格式: png, jpg, webp
     */
    "imageFormat": string;

    /**
     * JPEG 质量 1-100
     */
    "jpegQuality": number;

    /**
     * 全局快捷键
     */
    "hotkey": string;

    /**
     * 启动时最小化到托盘
     */
    "startMinimized": boolean;

    /**
     * 路径格式: absolute, relative, markdown, html, url
     */
    "pathFormat": string;

    /**
     * 是否启用历史记录
     */
    "enableHistory": boolean;

    /**
     * 历史记录最大数量
     */
    "maxHistory": number;

    /**
     * 是否自动压缩大尺寸图片
     */
    "autoCompress": boolean;

    /**
     * 最大尺寸限制 (像素)
     */
    "maxDimension": number;
}
