// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 应用服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * ClearHistory 清空历史记录
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(3429172794);
}

/**
 * DeleteImage 删除图片
 */
export function DeleteImage(path: string): $CancellablePromise<void> {
    return $Call.ByID(2942552135, path);
}

/**
 * GetConfig 获取配置
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(1200034045);
}

/**
 * GetHotkey 获取热键
 */
export function GetHotkey(): $CancellablePromise<string> {
    return $Call.ByID(859888613);
}

/**
 * GetRecentImages 获取最近保存的图片
 */
export function GetRecentImages(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(2474146238);
}

/**
 * GetSaveDirectory 获取保存目录
 */
export function GetSaveDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4274265753);
}

/**
 * InitInBackground 在后台初始化组件
 */
export function InitInBackground(): $CancellablePromise<void> {
    return $Call.ByID(2056851724);
}

/**
 * OnShutdown 应用关闭时调用 (Wails v3 生命周期方法)
 */
export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(999779538);
}

/**
 * OnStartup 应用启动时调用 (Wails v3 生命周期方法)
 */
export function OnStartup(): $CancellablePromise<void> {
    return $Call.ByID(2232168041);
}

/**
 * OpenDirectory 打开保存目录
 */
export function OpenDirectory(): $CancellablePromise<void> {
    return $Call.ByID(4113378380);
}

/**
 * PasteLastImage 粘贴剪切板中的图片路径（异步执行，立即返回）
 * 流程：读取剪切板图片 -> 保存 -> 插入路径
 */
export function PasteLastImage(): $CancellablePromise<void> {
    return $Call.ByID(2532211309);
}

/**
 * SelectDirectory 选择目录对话框
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SetApp 设置 Wails 应用实例
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4256893662, app);
}

/**
 * SetHotkey 设置热键
 */
export function SetHotkey(hotkeyStr: string): $CancellablePromise<void> {
    return $Call.ByID(1114980409, hotkeyStr);
}

/**
 * SetSaveDirectory 设置保存目录
 */
export function SetSaveDirectory(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3615340733, dir);
}

/**
 * UpdateConfig 更新配置
 */
export function UpdateConfig(cfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(481689322, cfg);
}
